<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class YoMommaJokeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jokes = [
            'Yo momma so fat, when she skips a meal, the stock market drops!',
            "Yo momma so old, her birth certificate says 'expired'!",
            'Yo momma so ugly, she made an onion cry!',
            'Yo momma so stupid, she put lipstick on her forehead to make up her mind!',
            "Yo momma so fat, when she wears a yellow raincoat, people yell 'Taxi!'",
            'Yo momma so short, she can do backflips under the bed!',
            'Yo momma so hairy, Bigfoot took a picture of her!',
            'Yo momma so lazy, she thinks a two-income family is where yo daddy has two jobs!',
            'Yo momma so poor, ducks throw bread at her!',
            'Yo momma so ugly, when she walks into a bank, they turn off the cameras!',
            'Yo momma so fat, when she sat on Walmart, she lowered the prices!',
            'Yo momma so dumb, she thought a quarterback was a refund!',
            'Yo momma so old, she knew Burger King when he was still a prince!',
            'Yo momma so nasty, she made Right Guard turn left!',
            "Yo momma so fat, her belt size is 'equator'!",
            'Yo momma so stupid, she got locked in a grocery store and starved!',
            'Yo momma so ugly, hello kitty said goodbye!',
            "Yo momma so fat, she's on both sides of the family!",
            "Yo momma so poor, she can't even pay attention!",
            'Yo momma so old, her social security number is 1!',
            'Yo momma so hairy, the only language she speaks is Wookie!',
            'Yo momma so fat, when she walks past the TV, you miss three episodes!',
            "Yo momma so ugly, when she tried to take a selfie, the phone said 'No storage'!",
            'Yo momma so dumb, she thinks Taco Bell is a Mexican phone company!',
            "Yo momma so fat, she stepped on a scale and it said 'One at a time, please!'",
            "Yo momma so lazy, she's got a remote control for her remote control!",
            'Yo momma so old, she has a picture of Moses in her yearbook!',
            "Yo momma so ugly, even Rice Krispies won't talk to her!",
            'Yo momma so fat, when she goes camping, the bears hide their food!',
            'Yo momma so stupid, she sold her car for gas money!',
            'Yo momma so poor, she waves around a popsicle stick and calls it air conditioning!',
            'Yo momma so fat, she has to iron her pants on the driveway!',
            'Yo momma so hairy, she shaves with a weed whacker!',
            "Yo momma so old, she's got Jesus's autograph!",
            'Yo momma so ugly, she walked past a haunted house and came out with a job application!',
            'Yo momma so fat, her blood type is Nutella!',
            'Yo momma so dumb, she tried to put M&Ms in alphabetical order!',
            'Yo momma so lazy, she has a stay-at-home job and still calls in sick!',
            "Yo momma so poor, she went to McDonald's and put a milkshake on layaway!",
            'Yo momma so fat, when she wears high heels, she strikes oil!',
            "Yo momma so ugly, when she walks into a salon, they say 'Sorry, we can't help you here'!",
            'Yo momma so old, her first job was as a tour guide for the Garden of Eden!',
            'Yo momma so fat, she went to the movies and sat next to everyone!',
            "Yo momma so stupid, she thinks Fleetwood Mac is a new burger at McDonald's!",
            'Yo momma so nasty, she sweats hot sauce!',
            "Yo momma so fat, when she steps on a scale, it says 'To be continued...'",
            'Yo momma so ugly, when she looked in the mirror, her reflection ducked!',
            'Yo momma so poor, burglars break into her house and leave money!',
            "Yo momma so lazy, she's got a remote control for her electric wheelchair!",
            "Yo momma so fat, when she goes to the beach, the whales sing 'We Are Family'!",
            'Yo momma so dumb, she thought a hard drive was a difficult road trip!',
            'Yo momma so old, when she was in school, there was no history class!',
            "Yo momma so hairy, she looks like she's wearing a sweater when she's naked!",
            'Yo momma so fat, her car has stretch marks!',
            "Yo momma so ugly, even Scooby Doo couldn't solve that mystery!",
            'Yo momma so stupid, she climbed over a glass wall to see what was on the other side!',
            "Yo momma so poor, she can't even afford to pay attention!",
            'Yo momma so fat, she fell in love and broke it!',
            'Yo momma so lazy, she took a ruler to bed to see how long she slept!',
            'Yo momma so old, she babysat for Jesus!',
            'Yo momma so ugly, when she walks into a pet store, all the dogs hide!',
            "Yo momma so fat, she's got more chins than a Chinese phone book!",
            'Yo momma so dumb, she thinks Johnny Cash is a pay toilet!',
            'Yo momma so nasty, she uses her spit to wax her car!',
            'Yo momma so fat, when she sat on an iPod, she made the iPad!',
            'Yo momma so poor, Nigerian princes send her money!',
            'Yo momma so ugly, when she cries, the tears run UP her face!',
            'Yo momma so lazy, she got a part-time job as a mannequin!',
            "Yo momma so fat, she's got her own area code!",
            "Yo momma so stupid, she thought Dunkin' Donuts was a basketball team!",
            "Yo momma so old, she knew Cap'n Crunch when he was just a private!",
            'Yo momma so hairy, Jane Goodall tried to study her!',
            "Yo momma so fat, when she wears a red shirt, kids yell 'Kool-Aid!'",
            'Yo momma so ugly, she turned Medusa to stone!',
            "Yo momma so dumb, she stared at a cup of orange juice for 12 hours because it said 'concentrate'!",
            'Yo momma so poor, she married young just to get rice thrown at her!',
            'Yo momma so fat, her patronus is a cake!',
            "Yo momma so lazy, she watched a sunrise and said 'I'll catch the next one'!",
            'Yo momma so old, her memory is in black and white!',
            "Yo momma so ugly, when she joined an ugly contest, they said 'Sorry, no professionals'!",
            "Yo momma so fat, she's the reason Waldo is hiding!",
            'Yo momma so stupid, she brought a spoon to the Super Bowl!',
            'Yo momma so nasty, she has to creep up on bathwater!',
            'Yo momma so fat, she uses Google Maps to find her own feet!',
            "Yo momma so poor, when I asked what's for dinner, she put her feet on the table and said 'Corn'!",
            "Yo momma so ugly, even the Joker won't smile at her!",
            'Yo momma so lazy, she just sits there and does nothing... professionally!',
            'Yo momma so fat, her shadow weighs 50 pounds!',
            'Yo momma so dumb, she thought Boyz II Men was a daycare center!',
            'Yo momma so old, her first car was a chariot!',
            "Yo momma so hairy, her armpits look like she's got Don King in a headlock!",
            "Yo momma so fat, she's got smaller fat women orbiting around her!",
            'Yo momma so ugly, her portraits hang themselves!',
            'Yo momma so stupid, she returned a doughnut because it had a hole in it!',
            'Yo momma so poor, she waves around a popsicle and calls it central heating!',
            'Yo momma so fat, when she went to the zoo, the elephants threw peanuts at her!',
            "Yo momma so lazy, she's got a remote control just to operate the other remote!",
            'Yo momma so old, she pre-ordered the Bible!',
            'Yo momma so ugly, her pillow cries at night!',
            'Yo momma so fat, when she fell down the stairs, I thought EastEnders was ending!',
        ];

        foreach ($jokes as $joke) {
            \App\Models\YoMommaJoke::create(['joke' => $joke]);
        }
    }
}
